algoritmo "Atividade 4.3"
// Função :
// Autor :
// Data : 11/03/2015
// Seção de Declarações 
var
   numero_i : inteiro
   numero : inteiro
inicio
// Seção de Comandos
   Escreval ("digite o numero inicial: ")
   leia(numero_i)
   para numero de numero_i ate (numero_i + 15) passo 1 faca
        escreval ("Antecessor:",numero-1," Numero:",numero," Sucessor:",numero+1," Dobro:",numero*2," Triplo:",numero*3)
   fimpara
fimalgoritmo
