algoritmo "Atividade 4.5"
// Função :
// Autor :
// Data : 11/03/2015
// Seção de Declarações 
var
   ano : inteiro
   habitantes : inteiro
   habitantes_c : real
inicio
// Seção de Comandos
   habitantes_c <- 20000
   Escreval("Digite o ano desejado: ")
   leia(ano)
   para habitantes de 2011 ate ano passo 1 faca
        habitantes_c <- habitantes_c * 1.05
   fimpara
        escreval("o numero de habitantes é: ", habitantes_c)

fimalgoritmo
