algoritmo "Exemplo_Repita_1"
// Função :
// Autor :
// Data : 23/03/2015
// Seção de Declarações 
var
   cont : inteiro
inicio
   // vai fazer o teste da condição sempre no final do loop
   // fazendo com que o loop seja sempre executado pelo menos
   // uma vez
   cont <- 0
   repita
      escreval(cont)
      cont <- cont + 1
   ate (cont > 10)
   
   cont <- 0
   enquanto (cont <= 10) faca
      escreval(cont)
      cont <- cont + 1
   fimenquanto
fimalgoritmo
